save-hackage-creds: false
resolver: lts-15.6

extra-deps:
- 'heist-1.1.0.1'
- 'map-syntax-0.3'
- 'happstack-server-7.6.0'
- 'xmlhtml-0.2.5.2'

packages:
- 'digestive-functors/'
- 'digestive-functors-blaze/'
- 'digestive-functors-happstack/'
- 'digestive-functors-heist/'
- 'digestive-functors-snap/'
